var mongoose     = require('mongoose');
var Schema       = mongoose.Schema;

var TrackSchema = new Schema({
	analysis_sample_rate: Number,
	bars: [{
		duration : Number,
		start : Number,
		confidence : Number
	}],
	mode_confidence: Number,
	end_of_fade_in: Number,
	key_confidence: Number,
	energy: Number,
	decoder: String,
	analysis_url: String,
	speechiness: Number,
	beats: [{
		duration : Number,
		start : Number,
		confidence : Number
	}],
	meta: {	
		album: String,
		artist: String,
		seconds: Number,
		status_code: Number,
		detailed_status: String,
		title: String,
		filename: String,
		platform: String,
		analyzer_version: String,
		sample_rate: Number,
		timestamp: Number,
		genre: String,
		bitrate: Number,
		analysis_time: Number
	},
	synch_version: Number,
	duration: Number,
	rhythm_version: Number,
	id: String,
	rhythmstring: String,
	echoprintstring: String,
	sample_md5: String,
	time_signature_confidence: Number,
	title: String,
	_object_type: String,
	segments: [{
		confidence: Number,
		timbre: [Number],
		pitches: [Number],
		loudness_end: Number,
		start: Number,
		loudness_max_time: Number,
		loudness_start: Number,
		duration: Number,
		loudness_max: Number
	}],
	cache: String,
	acousticness: Number,
	danceability: Number,
	artist_id: String,
	sections: [{
		confidence : Number,
		mode_confidence : Number,
		time_signature : Number,
		key_confidence : Number,
		tempo : Number,
		time_signature_confidence : Number,
		start : Number,
		tempo_confidence : Number,
		mode : Number,
		key : Number,
		duration : Number,
		loudness : Number,
	}],
	start_of_fade_out: Number,
	tatums: [{
		duration: Number,
		start: Number,
		confidence: Number,
	}],
	status: String,
	album: String,
	analysis_channels: Number,
	tempo: Number,
	offset_seconds: Number,
	tempo_confidence: Number,
	instrumentalness: Number,
	key: Number,
	synchstring: String,
	genre: String,
	md5: String,
	song_id: String,
	artist: String,
	echoprint_version: Number,
	code_version: Number,
	liveness: Number,
	window_seconds: Number,
	mp3_uri: String,
	codestring: String,
	analyzer_version: String,
	mode: Number,
	time_signature: Number,
	num_samples: Number,
	release: String,
	loudness: Number,
	decoder_version: String,
	valence: Number,
});

module.exports = mongoose.model('Track', TrackSchema);